FROM node:20.11.0-slim

WORKDIR /app

# Install libssl for prisma
RUN apt-get update && apt-get install -y \
  lsof \
  net-tools \
  telnet \
  openssl \
  procps

COPY package*.json ./

RUN npm install -g @nestjs/cli

COPY . .

RUN npm install

EXPOSE ${APP_PORT} 9229

RUN npm run prepare

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT [ "/bin/sh", "/app/entrypoint.sh" ]
